import { ChangeEvent, MouseEventHandler, ReactElement, ReactNode } from "react"

export type Params = {
    [key: string]: any
}


export interface ColumnsProps {
    field: string,
    headerName: string,
    width: string | number,
    renderCell?: (params: Params, action: (e?: ChangeEvent<HTMLInputElement>) => void) => ReactNode | ReactElement
    actionsItem?: (params: Params, action: () => void) => ReactNode | ReactElement
}

export interface User {
    date_of_birth: string;
    email: string;
    first_name: string;
    id: string;
    id_auth0: string;
    last_name: string;
    second_last_name: string;
    second_name: string;
    telephone: string;
    time_zone: string;
    language: string;
}

export interface TableFooterProps<Data> {
    callBack: (number: number) => void,
    range: number[],
    setPage: any,
    page: number,
    slice: Data[],
    data: Data[]
}

// Generated by https://quicktype.io

export interface UserTable {
    data: User;
}



export interface Image {
    file_name: string;
    updated_at: string;
}